# Generated by Django 3.2.16 on 2022-12-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
