# Generated by Django 3.2.16 on 2023-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221223_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'published_on', 'ordering': ['-published_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Secondary')], default=0),
        ),
    ]
