# Generated by Django 3.2.16 on 2023-01-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20230103_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'published_on', 'ordering': ['-published_on'], 'permissions': [('publish', 'Can publish article'), ('edit', 'Can edit article draft')]},
        ),
    ]
