# Generated by Django 3.2.16 on 2023-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='original_article',
            field=models.URLField(blank=True),
        ),
    ]
