# Generated by Django 3.2.16 on 2023-01-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_original_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
    ]
